server:
   port: 8080

spring:
  profiles:
    active: local
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

jwt:
   secret: hLbSbsS4SRFobzmfyst4FOQLP9NhRfA7Si+wkHCHS9u3ecgG+nEHjQGtqRU7eBkyO2se0RUIgxwEjtaXB40F0g==
   expiration: 86400000

coupon:
  thrift:
    host: localhost
    port: 9090